// Decompiled with JetBrains decompiler (renamed for readability)
// Type: <obfuscated>.Settings
// Assembly: Ledger Live, Version=1.0.0.0

using System.CodeDom.Compiler;
using System.Configuration;
using System.Runtime.CompilerServices;

namespace Ledger.FileGenerator // placeholder: replace with real namespace if desired
{
    /// <summary>
    /// Strongly-typed application/user settings wrapper generated by Visual Studio.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode(
        "Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator",
        "17.8.0.0")]
    internal sealed class Settings : ApplicationSettingsBase
    {
        private static readonly Settings defaultInstance =
            (Settings)Synchronized(new Settings());

        public static Settings Default => defaultInstance;
    }
}
